name: TRNIdart_analyzer
description: A sample command-line application.
version: 0.0.1
#homepage: https://www.example.com
#author: mmeneses <email@example.com>

environment:
  sdk: '>=1.20.1 <2.0.0'

dependencies:
  analyzer: "^0.31.0-alpha.1"
  tuple:
#  path: ^1.4.1

dev_dependencies:
  test: ^0.12.0
